apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bzy-personal

resources:
  - namespace.yaml
  - bzy-brain-deployment.yaml
  - bzy-runner-deployment.yaml
  - bzy-interface-deployment.yaml

configMapGenerator:
  - name: bzy-config
    literals:
      - redis-addr=redis:6379
      - nats-url=nats://nats:4222
      - otlp-endpoint=otel-collector:4317

images:
  - name: ghcr.io/bzyfuzy/bzy-brain
    newTag: latest
  - name: ghcr.io/bzyfuzy/bzy-runner
    newTag: latest
  - name: ghcr.io/bzyfuzy/bzy-interface
    newTag: latest

commonLabels:
  app.kubernetes.io/part-of: bzy-personal
  app.kubernetes.io/managed-by: kustomize
